'use server'

import { createClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'
import { revalidatePath } from 'next/cache'
import { emailJobCreated, emailCustomerStatusUpdate } from '@/lib/email'

export async function createJob(formData: FormData) {
  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  const buildType = formData.get('build_type') as string

  // 1. Create customer
  // Note: job_id is auto-generated by DB trigger (generate_job_id) — no need to set it here
  const { data: customer, error: customerError } = await supabase
    .from('customers')
    .insert({
      name:  formData.get('customer_name') as string,
      email: (formData.get('customer_email') as string) || null,
      phone: (formData.get('customer_phone') as string) || null,
    })
    .select('id')
    .single()

  if (customerError) redirect(`/ops/jobs/new?error=${encodeURIComponent('Could not create customer: ' + customerError.message)}`)

  // 2. Create vehicle — job_id is set by DB trigger (generate_job_id)
  const { data: vehicle, error: vehicleError } = await supabase
    .from('vehicles')
    .insert({
      job_id:                    '',   // placeholder — trigger overwrites before insert
      vehicle_make:              formData.get('vehicle_make') as string,
      vehicle_model:             formData.get('vehicle_model') as string,
      vehicle_year:              Number(formData.get('vehicle_year')) || null,
      vin:                       (formData.get('vin') as string) || null,
      stock_number:              (formData.get('stock_number') as string) || null,
      registration:              (formData.get('registration') as string) || null,
      build_type:                buildType,
      estimated_completion_date: (formData.get('estimated_completion_date') as string) || null,
      customer_id:               customer.id,
      created_by:                user.id,
      build_status:              'pending',
    })
    .select('id, job_id')
    .single()

  if (vehicleError) redirect(`/ops/jobs/new?error=${encodeURIComponent('Could not create job: ' + vehicleError.message)}`)

  // 3. Generate QR code
  await supabase
    .from('qr_codes')
    .insert({ vehicle_id: vehicle.id, generated_by: user.id, is_active: true })

  // 3b. Log job creation + send ops email
  await supabase.from('activity_log').insert({
    vehicle_id: vehicle.id,
    user_id:    user.id,
    action:     'job_created',
    old_value:  null,
    new_value:  { job_id: vehicle.job_id, build_type: buildType },
  })

  const customerName = formData.get('customer_name') as string
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL ?? 'https://axiom-build-system.vercel.app'
  await emailJobCreated({
    jobId: vehicle.job_id,
    vehicleYear:  Number(formData.get('vehicle_year')) || null,
    vehicleMake:  formData.get('vehicle_make') as string,
    vehicleModel: formData.get('vehicle_model') as string,
    buildType,
    customerName,
    jobUrl: `${baseUrl}/ops/jobs/${vehicle.id}`,
  })

  // 4. Auto-create tasks from templates for this build type
  const { data: templates } = await supabase
    .from('task_templates')
    .select('task_name, task_category, task_order, role_required, is_required, photo_required')
    .eq('build_type', buildType)
    .order('task_order', { ascending: true })

  const tasksToInsert = (templates && templates.length > 0)
    ? templates.map(t => ({
        vehicle_id:    vehicle.id,
        task_name:     t.task_name,
        task_category: t.task_category,
        task_order:    t.task_order,
        role_required: t.role_required,
        is_required:   t.is_required,
        photo_required: t.photo_required,
        status:        'pending' as const,
      }))
    : [
        // Fallback if no templates exist for this build type
        { vehicle_id: vehicle.id, task_name: 'Conversion Kit Fitted',   task_category: 'Structure & Materials', task_order: 1, role_required: 'fitter' as const, is_required: true, photo_required: false, status: 'pending' as const },
        { vehicle_id: vehicle.id, task_name: 'Electric & Water Fitted', task_category: 'Electrical & Plumbing', task_order: 2, role_required: 'fitter' as const, is_required: true, photo_required: false, status: 'pending' as const },
        { vehicle_id: vehicle.id, task_name: 'Upgrades',               task_category: 'Upgrades',              task_order: 3, role_required: 'fitter' as const, is_required: true, photo_required: false, status: 'pending' as const },
      ]

  await supabase.from('tasks').insert(tasksToInsert)

  redirect(`/ops/jobs/${vehicle.id}`)
}

export async function updateBuildStatus(formData: FormData) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  const vehicleId   = formData.get('vehicle_id') as string
  const buildStatus = formData.get('build_status') as string

  await supabase.from('vehicles').update({
    build_status: buildStatus,
    ...(buildStatus === 'delivered' ? { handover_date: new Date().toISOString().split('T')[0] } : {}),
  }).eq('id', vehicleId)

  // Log status change
  await supabase.from('activity_log').insert({
    vehicle_id: vehicleId,
    user_id:    user.id,
    action:     'status_changed',
    old_value:  null,
    new_value:  { status: buildStatus },
  })

  // Email customer if they have an email address
  const { data: vehicleData } = await supabase
    .from('vehicles')
    .select('job_id, vehicle_year, vehicle_make, vehicle_model, customers(name, email, portal_token)')
    .eq('id', vehicleId)
    .single()

  if (vehicleData) {
    const customer = vehicleData.customers as { name: string; email: string | null; portal_token: string } | null
    if (customer?.email) {
      const baseUrl = process.env.NEXT_PUBLIC_APP_URL ?? 'https://axiom-build-system.vercel.app'
      await emailCustomerStatusUpdate({
        customerEmail: customer.email,
        customerName:  customer.name,
        jobId:         vehicleData.job_id,
        vehicleYear:   vehicleData.vehicle_year,
        vehicleMake:   vehicleData.vehicle_make,
        vehicleModel:  vehicleData.vehicle_model,
        status:        buildStatus,
        portalUrl:     `${baseUrl}/portal/${customer.portal_token}`,
      })
    }
  }

  revalidatePath(`/ops/jobs/${vehicleId}`)
}

export async function saveJobNotes(formData: FormData) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  const vehicleId = formData.get('vehicle_id') as string
  const notes     = formData.get('notes') as string

  await supabase.from('vehicles').update({ notes }).eq('id', vehicleId)

  await supabase.from('activity_log').insert({
    vehicle_id: vehicleId,
    user_id:    user.id,
    action:     'notes_saved',
    old_value:  null,
    new_value:  { notes },
  })

  revalidatePath(`/ops/jobs/${vehicleId}`)
}

export async function deleteJob(formData: FormData) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  const vehicleId = formData.get('vehicle_id') as string

  // Delete in order: tasks, qr_codes, photos, vehicle (customer kept)
  await supabase.from('tasks').delete().eq('vehicle_id', vehicleId)
  await supabase.from('qr_codes').delete().eq('vehicle_id', vehicleId)
  await supabase.from('photos').delete().eq('vehicle_id', vehicleId)
  await supabase.from('vehicles').delete().eq('id', vehicleId)

  redirect('/ops/jobs')
}
